version: "3"

services:
  rabbitmq:
    image: rabbitmq:alpine
    ports:
      - "5672:5672"

  redis-server:
    image: redis
    volumes:
      - ./tests/conf:/usr/local/etc/redis
    command:
      - /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
