version: 2

aliases:
  - docker: &docker
    - image: circleci/node:12

  - &environment
    TZ: /usr/share/zoneinfo/Europe/Paris

  - &restore_yarn_cache
    restore_cache:
      name: Restore yarn cache
      key: dependency-cache-{{ arch }}-{{ checksum "yarn.lock" }}-yarn

  - &restore_node_modules
    restore_cache:
      name: Restore node_modules cache
      keys:
        - dependency-cache-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum "workspace_info.txt" }}-node-modules

  - &workspace_info
    run: yarn workspaces info | head -n -1 > workspace_info.txt

  - &install_deps
    run:
      name: Install Packages
      command: yarn config set cacheFolder ~/.cache/yarn  && yarn --immutable

  - &run_unit_tests
    run:
      name: Test
      command: yarn run test:ci

unit_tests_template: &unit_tests_template
  steps:
    - checkout
    - *workspace_info
    - *restore_yarn_cache
    - *restore_node_modules
    - *install_deps
    - *run_unit_tests

jobs:
  setup:
    docker: *docker
    environment: *environment
    steps:
      - checkout
      - run:
          name: Nodejs Version
          command: node --version
      - *restore_yarn_cache
      - *install_deps
      - *workspace_info
      - save_cache:
          # Store the yarn cache globally for all lock files with this same
          # checksum. This will speed up the setup job for all PRs where the
          # lockfile is the same.
          name: Save yarn cache for future installs
          key: dependency-cache-{{ arch }}-{{ checksum "yarn.lock" }}-yarn
          paths:
            - ~/.cache/yarn
      - save_cache:
          # Store node_modules for all jobs in this workflow so that they don't
          # need to each run a yarn install for each job. This will speed up
          # all jobs run on this branch with the same lockfile.
          name: Save node_modules cache
          # This cache key is per branch, a yarn install in setup is required.
          key: dependency-cache-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum "workspace_info.txt" }}-node-modules
          paths:
            - node_modules

  test_node_12:
    docker:
      - image: circleci/node:12
      - image: circleci/redis
      - image: rabbitmq
    steps:
      - checkout
      - *workspace_info
      - *restore_yarn_cache
      - *restore_node_modules
      - *install_deps
      - *run_unit_tests
      - run:
          name: Collect coverage
          command: yarn coverage
      - store_artifacts:
          path: coverage

  test_node_10:
    <<: *unit_tests_template
    docker:
      - image: circleci/node:10
      - image: circleci/redis
      - image: rabbitmq

workflows:
  version: 2
  stable:
    jobs:
      - setup
      - test_node_12:
          requires:
            - setup
      - test_node_10:
          requires:
            - setup
